### PR TITLE
Upstream nterry changes

### PR DESCRIPTION
**Pull request by alanmcgovern**
/cc @nterry

### CODE REVIEW

**Comment by nterry** [comment]
@alanmcgovern Holy crap! I never expected these changes to get merged. I honored!

Out of curiosity, what prompted you to bring in the changes after all this time?

**Comment by nterry** [comment]
@alanmcgovern Also, Id be happy to transfer the cicd stuff to you so this can be the official distribution if that is of interest to you. Id have to work out _how_ to to that, but id be willing to

**Comment by nterry** [comment]
@alanmcgovern Can you amend that email to nick.i.terry@gmail.com in the authors? I no longer have access the one currently in the file

**Comment by alanmcgovern** [comment]
What really happened is that i forgot about the repo after the previous conversation (and PR) a few years back :p

I need this lib for something I'm working on and realised that the router I have has some bugs and i need to hack up the library to make it work right. I looked through the PRs, saw yours, figured i may as well merge it in case it solved my problem. Unfortunately it didn't, but it is what it is!

If there's still active CI on this, then it might be easier to just add you as a contributor to this repo and transition things from your fork to this repo. I'll add you as a contributor anyway :p

**Comment by alanmcgovern** [comment]
(Though it is fine if you never touch the repo again, even with read/write access! :p I doubt i'll do a huge amount of patching other than making this work with my rather unique router issues :p )

**Pull request merged**
